<script>
    import { page } from "$app/stores";
    import { onMount } from "svelte";
    import SplideShow from "@/Splideshow.svelte";
    export const prerender = false;
    export const router = false;

    import { Splide, SplideSlide } from "@splidejs/svelte-splide";
    import "@splidejs/svelte-splide/css";

    let slideshowImages = ["/aleph/peaceout.jpg", "/art/blush.jpg"];

    function toggleButton(slide) {
        mySlider.go(slide - 1);
        window.scrollTo(0, 0);
    }

    let mySlider;
    onMount(() => {
        // console.log(mySlider.splide);
    });

    import * as fal from "@fal-ai/serverless-client";

    let falData = {};
    let falImage = [];
    let imageURL = ""; // Initialize for reactivity

    async function myfunction() {
        console.log("Inside of myfunction");

        const result = await fal.subscribe("fal-ai/fast-sdxl", {
            input: {
                prompt: "photo of a rhino dressed suit and tie sitting at a table in a bar with a bar stools, award winning photography, Elke vogelsang",
            },
            logs: true,
            onQueueUpdate: (update) => {
                if (update.status === "IN_PROGRESS") {
                    update.logs.map((log) => log.message).forEach(console.log);
                }
            },
        });
        return result;
    }

    // Call the image generation function
    (async () => {
        console.log("before start");
        falData = await myfunction();
        falImage = falData["images"];
        imageURL = falImage[0].url; // Update the imageURL
        console.log(imageURL);
        console.log("after start");
    })();
</script>

<div class="container m-auto w-3/4">
    {#if imageURL != ""}
        <img src={imageURL} alt="Image generated by AI" />
    {:else}
        <p>Loading Image...</p>
    {/if}
</div>
