<div class="container mx-auto max-w-screen-lg">
    <div class="mx-4 grid gap-4 md:grid-cols-1 lg:mx-0 lg:grid-cols-1">
        <div class="mb-16">
            <h1>Early Style GAN Dream</h1>
            <p>
                Optical illusions generated by an under-trained styleGAN2 model.
            </p>
        </div>
    </div>
    <iframe
        class="aspect-video w-full"
        src="https://www.youtube.com/embed/mrWvp8dhwEA"
        title="stylegan2 x op art patterns moires   latent walks 09 15 2020 1080p 2"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen
    ></iframe>
</div>
